-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 10:21:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookstore` ;

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`books_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`books_type` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`books_type` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(255) NULL,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`books` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`books` (
  `id_books` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NOT NULL,
  `books_name` VARCHAR(255) NULL,
  `books_des` TEXT NULL,
  `books_import_price` INT NULL,
  `books_sell_price` INT NULL,
  `books_point` INT NULL,
  `books_img` VARCHAR(255) NULL,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NULL,
  PRIMARY KEY (`id_books`),
  INDEX `fk_books_books_type_idx` (`id_type` ASC),
  CONSTRAINT `fk_books_books_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `bookstore`.`books_type` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`members` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`members` (
  `id_members` INT NOT NULL AUTO_INCREMENT,
  `members_name` VARCHAR(255) NULL,
  `members_phone` VARCHAR(45) NULL,
  `members_point` INT NULL,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NULL,
  PRIMARY KEY (`id_members`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`sell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`sell` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`sell` (
  `id_books` INT NOT NULL,
  `id_members` INT NOT NULL,
  `discount` INT NULL,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NULL,
  PRIMARY KEY (`id_books`, `id_members`),
  INDEX `fk_books_has_members_members1_idx` (`id_members` ASC),
  INDEX `fk_books_has_members_books1_idx` (`id_books` ASC),
  CONSTRAINT `fk_books_has_members_books1`
    FOREIGN KEY (`id_books`)
    REFERENCES `bookstore`.`books` (`id_books`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_members_members1`
    FOREIGN KEY (`id_members`)
    REFERENCES `bookstore`.`members` (`id_members`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
